[package]
name = "polylang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "compile"
path = "src/bin/compile/main.rs"

[[bin]]
name = "miden-run"
path = "src/bin/miden-run/main.rs"

[dependencies]
regex = { version = "1", default-features = false }
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1.7"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
polylang_parser = { path = "./parser" }
miden-vm = { git = "https://github.com/0xPolygonMiden/miden-vm", tag = "v0.4.0" }
miden-processor = { git = "https://github.com/0xPolygonMiden/miden-vm", tag = "v0.4.0" }
miden-stdlib = { git = "https://github.com/0xPolygonMiden/miden-vm", tag = "v0.4.0" }
lazy_static = "1.4.0"

[dev-dependencies]
pretty_assertions = "1.3.0"
