[package]
name = "polylang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[features]
default = ["parser"]
parser = []

[dependencies]
regex = { version = "1", default-features = false }
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1.7"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
polylang_parser = { path = "./parser" }
base64 = "0.21.0"

[dev-dependencies]
rand = "0.8.5"
expect-test = "1.4.0"
