name: Publish (Beta)

on:
  push:
    branches:
      - main
      - eng-688-fix-ci-release-process

jobs:
  publish:
    runs-on: ubuntu-latest-16-cores
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: "NPM Identity"
        working-directory: ./js
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

      - name: Yarn Version
        working-directory: ./js
        run: yarn --version

      - name: Install packages
        working-directory: ./js
        run: yarn

      - name: Build packages
        working-directory: ./js
        run: yarn lerna run build

      - name: "Publish"
        working-directory: ./js
        run: yarn lerna publish --canary --preid beta --dist-tag beta --yes --loglevel verbose
