name: Server CI

on:
  push:
    branches:
      - main
      - eng-1198-prover-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Log in to GCR
        run: gcloud auth configure-docker

      - name: Build and push server image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: gcr.io/polybase-internal/polylang-server:latest

      - name: Deploy
        run: |
          gcloud config set project polybase-internal
          gcloud config set run/region us-central1
          gcloud run deploy polylang-server --image gcr.io/polybase-internal/polylang-server:latest