on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Pull testnet collections
        continue-on-error: true
        run: |
          ./pull-collections.sh

      - name: Run Tests
        uses: actions-rs/cargo@v1
        timeout-minutes: 10
        with:
          command: test
          args: --workspace --all-features
