name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest-16-cores
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run Tests
        uses: actions-rs/cargo@v1
        timeout-minutes: 10
        with:
          command: test
          args: --workspace --all-features
